[platformio]
default_envs = waveshare_rp2040_touch_lcd
src_dir = firmware

[env:waveshare_rp2040_touch_lcd]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
