[platformio]
default_envs = waveshare_rp2040_touch_lcd
src_dir = src

[env:waveshare_rp2040_touch_lcd]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
build_src_filter =
	+<*>
	+<../driver/**/*.cpp>
build_flags =
	-I $PROJECT_DIR/driver/board
	-I $PROJECT_DIR/driver/display
	-I $PROJECT_DIR/driver/display/fonts
	-I $PROJECT_DIR/driver/sensors/imu_qmi8658
	-I $PROJECT_DIR/driver/sensors/touch_cst816s
